[env:esp32-c3-devkitm-1]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
lib_deps = 
    bblanchon/ArduinoJson@^6.21.3

; Build configuration
build_flags = 
    -Werror
    -Wall
    -Wextra

; Upload configuration
upload_port = /dev/ttyUSB0  ; Update with your port
upload_speed = 921600